### ISSUE TITLE
安装后，运行报错。

### ISSUE THREAD

**Issue by freechen** [zoujingli/framework#2]
安装后，运行报错。

![1](https://user-images.githubusercontent.com/5688949/45420335-7a7e3b00-b6bc-11e8-98ab-ffe5d502eb45.jpg)

**Comment by zoujingli** [comment]
应该是PHP版本的问题，提供下php版本及测试时的git版本号

**Comment by freechen** [comment]
php用的是7.0.12。
好像是控制器的名称和模块名一样造成的。

**Comment by zoujingli** [comment]
再次测试时，并没有出现这个问题

**Comment by zoujingli** [comment]
已经把工具包重新命名
