### ISSUE TITLE
上传控件变量冲突

### ISSUE THREAD

**Issue by ianh3y** [zoujingli/framework#4]
WebUploader上传控件server参数中的name值
与uploadBeforeSend事件中data参数的name冲突，导致图片上传失败。

参考解决：
更改server参数。
server: '{:url("@")}?s=admin/plugs/upload&name={$name|default="file"}',

**Comment by zoujingli** [comment]
事实上这个接口地址几乎没有用到的，在此之前有一个动态修改的过程。
在检查文件是否已经上传的时候，服务器会返回新的上传地址，然后动态重置这个地址的

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/49637916-a867e700-fa41-11e8-828b-424b24c04707.png)

**Comment by ianh3y** [comment]
不是这个位置的server。
是WebUploader实例化时上传url中的name值与控件本身uploadBeforeSend事件中data中的name值重复。
后端：/admin/Plugs.php中getUploadFile方法里获取上传事件的name，变成了文件名，造成文件上传失败。
具体表现在商城管理下添加商品和商品内容的上传图片。

**Comment by ianh3y** [comment]
Plugs.php 167行
return $this->request->file($this->request->post('name', 'file'));
修改为
return $this->request->file($this->request->get('name', 'file'));
可以直接上传成功。

**Comment by zoujingli** [comment]
Ok，知道了，传参方式不对。
这个参数用得小，一般都是默认 file 了

**Comment by zoujingli** [comment]
在封装 plupload 时是 post 提交的，这里我就直接使用 input 来接收吧_
