### ISSUE TITLE
本地部署时，新添加商品时post报500错误

### ISSUE THREAD

**Issue by lovingman** [zoujingli/framework#6]
新添加商品时post报500错误，
目录下application/store/controller/goods/的function _form_filter(&$data)方法,
报**Invalid argument supplied for foreach()**错
![图片](https://user-images.githubusercontent.com/15982295/54609877-c4424680-4a8e-11e9-840e-9b85f5938ec9.png)

 protected function _form_filter(&$data){
   if ($this->request->isGet()) {
           ..............
   }elseif ($this->request->isPost()) {
            Db::name('StoreGoodsList')->where(['goods_id' => $data['id']])->update(['status' => '0']);
            foreach (json_decode($data['lists'], true) as $vo) Data::save('StoreGoodsList', [
            'goods_id'       => $data['id'],
                'goods_spec'     => $vo[0]['key'],
                'price_market'   => $vo[0]['market'],
                'price_selling'  => $vo[0]['selling'],
                'number_virtual' => $vo[0]['virtual'],
                'status'         => $vo[0]['status'] ? 1 : 0,
            ], 'goods_spec', ['goods_id' => $data['id']]);
        }
}

**Comment by zoujingli** [comment]
应该是 app配置问题，更新下就可以了
把app的默认过滤去掉
