### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by xucanjia** [zoujingli/framework#7]
现在这个趋于稳定了吗 想使用您的项目来做项目

**Comment by zoujingli** [comment]
已经稳定，可以正常使用，适合二开
admin,wechat,service,config 都是可以远程更新的

**Comment by zoujingli** [comment]
更新指令
`php think xsync:admin`
`php think xsync:wechat`
php think ...........

**Comment by xucanjia** [comment]
项目部署上去 No input file specified. 试过很多方法都不行 。。。

**Comment by zoujingli** [comment]
需要配置 (public子目录运行)

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/54894238-9cbb0600-4ef4-11e9-8314-b5dbbdcaec08.png)

**Comment by xucanjia** [comment]
WWW\driver\public 已配置到public目录底下，
![image](https://user-images.githubusercontent.com/20274205/54894285-dd1a8400-4ef4-11e9-8f17-6c8af351245a.png)

**Comment by zoujingli** [comment]
没有配置伪静态，index.php/admin/login.html

**Comment by zoujingli** [comment]
可以使用 `php think run` 来进本地开发测试，不需要使用 apache 或 nginx

**Comment by xucanjia** [comment]
不知道是我的问题吗 报错的只能在这里看到 
![image](https://user-images.githubusercontent.com/20274205/54968653-6645bf80-4fb6-11e9-81c6-eedd037d62ba.png)

**Comment by zoujingli** [comment]
在下面点有详细描述，也可以preview

**Comment by xucanjia** [comment]
这里哦   我看的时候是空白的
![image](https://user-images.githubusercontent.com/20274205/54968743-b6bd1d00-4fb6-11e9-9f17-aece884f52b8.png)

**Comment by zoujingli** [comment]
唉，把代码复制到 html中查看吧，response 往下滑，能看到错误的

**Comment by xucanjia** [comment]
嗯嗯 现在在看您这个项目 think-library 但是也是没用起来 有点没搞明白

**Comment by zoujingli** [comment]
看下 admin 模块的控制器
